GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJqaG9uIiwiZW1haWwiOiJqaG9uZUBtYWlsLmNvbSIsImlhdCI6MTcxNzQ5NzA4MywiZXhwIjoxNzE3NDk3MDk4fQ.32FRC1TOCK9MI5Mnnqbb3PpFLvm1wy19USFXh59NWcY

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "name" : "admin6",
    "email": "admin6@mail.com",
    "password": "abcs",
    "confPassword": "abcs"
}


###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "admin6@mail.com",
    "password": "abcs"

}

###
GET http://localhost:8080/token


###
DELETE http://localhost:3300/logout