GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJuYW1lIjoiYWRtaW45IiwiZW1haWwiOiJhZG1pbjlAbWFpbC5jb20iLCJpYXQiOjE3MTc2NzE3NjAsImV4cCI6MTcxNzY3MTc3NX0.1jJaD7-3Oku7AG8YFnS3pn-qMnmXuOzADxAr8Tvvj54
###
POST http://localhost:8080/users
Content-Type: application/json

{
    "name" : "admin9",
    "email": "admin9@mail.com",
    "password": "abcd",
    "confPassword": "abcd"
}


###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "admin9@mail.com",
    "password": "1abcd"

}

###
GET http://localhost:8080/token


###
DELETE http://localhost:3300/logout